---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: pod-netstat-exporter
  namespace: monitoring
  labels:
    app: pod-netstat-exporter
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-netstat-exporter
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-netstat-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-netstat-exporter
subjects:
  - kind: ServiceAccount
    name: pod-netstat-exporter
    namespace: monitoring
