apiVersion: v1
kind: Service
metadata:
  name: pod-netstat-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: pod-netstat-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
  selector:
    app.kubernetes.io/name: pod-netstat-exporter
